= Broken routing from URL

This is based on `fulcro-rad-demo` and demonstrates problems with nested dynamic routers and hard-reload of a URL, for https://github.com/fulcrologic/fulcro/discussions/440

While it works to click through the UI to arrive to a particular view, when I try to load the resulting URL I will not get the same view.

## Problems

### Current problem

The issue in the commit `Issue 1: Broken reload on accounts/accounts` is:

Going to the URL http://localhost:3000/accounts/accounts?_rp_=WyJeICJd& is broken - it will display "Welcome to the Demo. .." with a loading indicator, forever, instead of the AccountList. In the browser Console it logs:

> ERROR dr/target-ready! was called but there was no router waiting for the target listed:  [:component/id :com.example.ui/Accounts] This could mean you sent one ident, and indicated ready on another.

The cause is 99% surely the newly added deferred `:will-enter` in `Accounts`.

When you go to http://localhost:3000/ and click _Accounts_ then _accounts_, you will see the expected account list.

## Code structure

The code is based on RAD demo but the UI has been simplified and a new level of routing with `dr/deferred` has been added between the MainRouter and the AccountList report:

* Root
** MainRouter `router`
*** LandingPage `defsc`
*** Accounts `defsc`, `dr/deferred`
**** AccountsDetailsRouter `router`
***** AccountsDetailDefault `defsc`
***** AccountList `rad/report`
